### ISSUE TITLE
 Date picker  persists during a device screen timeout or device lock

### ISSUE THREAD

**Issue by jackie-eb** [gusparis/react-native-month-year-picker#31]
Date picker  persists during a device screen timeout or device lock. When the device is unlocked, the date picker is displayed regardless of the app state before screen lock

**Comment by gusparis** [comment]
@jackie-eb Thank you for using the library! This is the expected behavior. The library is not managing app states. Check https://github.com/react-native-community/datetimepicker, also persisting when coming back from background. Nevertheless, the library had a bug on Android that will open the dialog always. That was fixed in #29.

**Comment by sizhe-eb** [comment]
> @jackie-eb Thank you for using the library! This is the expected behavior. The library is not managing app states. Check https://github.com/react-native-community/datetimepicker, also persisting when coming back from background. Nevertheless, the library had a bug on Android that will open the dialog always. That was fixed in #29.
> 
> Edit: I will close this because is not an issue.

Works properly! Thx~
